kumuluzee:
  datasources:
    - jndi-name: jdbc/AccountsDS
      connection-url: jdbc:postgresql://postgres-db:5432/accounts
      username: postgres
      password: postgres
      pool:
        max-size: 20
  streaming:
    kafka:
      producer:
        bootstrap-servers: kafka:9092
        request-timeout-ms: 500 # wait for error by the producer
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer